### ISSUE TITLE
firefox android

### ISSUE THREAD

**Issue by flagoda** [riiswa/covid19-attestation-deplacement-form#2]
Bonjour,
Tout d'abord super idée, surtout pour les personnes n'ayant pas d'ordinateur.
Cependant sur Android impossible de télécharger le pdf avec Firefox, Navigatuer MI, cela marche seulement avec Google Chrome.

**Comment by riiswa** [comment]
J'utilise la fonction `window.print()` de JS pour le rendu et ont dirais quel est uniquement supporter par le navigateur Chrome. Je vais essayer de trouver une alternative !
